// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHT571N5ZkQ_iZQPA_vpYE9sCM8FQzoU',
    appId: '1:1043318154501:web:0a0f6d9f665ed0b600036c',
    messagingSenderId: '1043318154501',
    projectId: 'my-assistant-nick',
    authDomain: 'my-assistant-nick.firebaseapp.com',
    storageBucket: 'my-assistant-nick.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhnhYU9OXSbzzVBMAVMpfnVp7CUnZWAm0',
    appId: '1:1043318154501:android:dfcc14316cab69bf00036c',
    messagingSenderId: '1043318154501',
    projectId: 'my-assistant-nick',
    storageBucket: 'my-assistant-nick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyU56sYDJ_oPXpbu4YfBoQ5K-xTXlD_FE',
    appId: '1:1043318154501:ios:d77a52b75fb9c26d00036c',
    messagingSenderId: '1043318154501',
    projectId: 'my-assistant-nick',
    storageBucket: 'my-assistant-nick.appspot.com',
    iosBundleId: 'com.example.myAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyU56sYDJ_oPXpbu4YfBoQ5K-xTXlD_FE',
    appId: '1:1043318154501:ios:d77a52b75fb9c26d00036c',
    messagingSenderId: '1043318154501',
    projectId: 'my-assistant-nick',
    storageBucket: 'my-assistant-nick.appspot.com',
    iosBundleId: 'com.example.myAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfHT571N5ZkQ_iZQPA_vpYE9sCM8FQzoU',
    appId: '1:1043318154501:web:34a6b76b1853a16900036c',
    messagingSenderId: '1043318154501',
    projectId: 'my-assistant-nick',
    authDomain: 'my-assistant-nick.firebaseapp.com',
    storageBucket: 'my-assistant-nick.appspot.com',
  );

}